site_name: Go Tutorial
site_description: Go Tutorial
site_author: Mehmet Gürdal
site_url: https://mgurdal.github.io/go-tutorial


nav:
    - Home: index.md
    - Data Structures : data-structures.md
    - Concurrency: concurrency.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mgurdal
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mgurdal_
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mgurdal

google_analytics:
  - UA-163254669-1
  - auto

theme:
  name: 'material'

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true

extra_css:
    - assets/css/extra.css
