site_name: Go Tutorial
site_description: Go Tutorial
site_author: Mehmet Gürdal
site_url: https://mgurdal.github.io/go-tutorial


nav:
    - Home: index.md
    - Data Structures : data-structures.md
    - Concurrency: concurrency.md


theme:
  name: 'material'

markdown_extensions:
  - codehilite
  - toc:
      permalink: true

extra_css:
    - assets/css/extra.css
